### ISSUE TITLE
Usability: Neue Studienrichtung zu Profil hinzufügen zu kompliziert

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#10]
Wenn ich bei meinem Profil eine neue Studienrichtung zu meinen Studienrichtungen hinzufügen will, ist das sehr kompliziert. Ich sehe zwar auf der Benutzer-Seite bei genauem Hinschauen einen hellgrauen Link "ändern" bei Studienrichtungen, der ist aber auf dem dunkelgrauen Hintergrund praktisch nicht zu sehen. Außerdem sollte man ihn vielleicht "hinzufügen / ändern" nennen.. - es ist meiner Meinung nach nicht logisch, dass ich da was hinzufügen kann sonst.

Wenn ich dann beim Hinzufügen bin, muss ich den Maus-Cursor (sehr unintuitiv) offenbar direkt neben die schon ausgewählte erste Studienrichtung in das Feld setzen, obwohl praktisch kein Platz mehr ist rechts davon - erst dann erscheint das Auswahlfeld - das sollte man besser machen...

**Comment by thaider** [comment]
- Text auf "hinzufügen/ändern" geändert
- Link ist aktuell nur ein Platzhalter, weil im ursprünglichen Design nicht vorgesehen - Gestaltung müsste noch von Tim kommen
- Formularfeld hat jetzt einen Rahmen und geht über die ganze Breite - so besser bzw. ausreichend klar?

**Comment by bkerschner** [comment]
finds so besser, ist dennoch die Frage ob das die Studis schnallen, dass sie zum Hinzufügen in den leeren Bereich klicken müssen... wird das Usability-Testing dann zeigen

**Comment by thaider** [comment]
@t1i2m3 herzlich willkommen auf github!
