### ISSUE TITLE
Lernunterlage erstellen: visuelles

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#15]
Fußzeile verdeckt auf https://test.skriptenforum.net/wiki/Spezial:Mit_Formular_bearbeiten/Neue_LV  den Link zu "weiter zum nächsten Schritt", wenn ich beim dritten Auswahlpunkt "Für welche Studienrichtung(en) wird diese Lehrveranstaltung angeboten?" angekommen bin

**Comment by thaider** [comment]
siehe #6
