### ISSUE TITLE
Lernunterlage erstellen: unbekannte Uni, was tun?

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#16]
Was soll ich tun, wenn ich eine Lernunterlage für eine unbekannte Uni erstellen möchte, die nicht in der Auswahlliste ist? Ich hab für https://test.skriptenforum.net/wiki/Epidemiologie_f%C3%BCr_Dummies_%28Gerald_Gartlehner%29 jetzt einfach das Feld freigelassen, falls man das soll, sollte das aber auch dabeistehen...

**Comment by thaider** [comment]
Es kann eine beliebige Studienrichtung eingegeben werden, die automatisch erstellt wird, sobald eine Lernunterlage angelegt wird. Wenn das richtige Format verwendet wird (Universität in Klammern), wird auch diese automatisch erstellt.

Textvorschlag (für oberhalb des Eingabefelds, damit es nicht durch die ausklappende Auswahlliste verdeckt wird):

> auswählen oder beliebigen Wert eingeben im Format „Studienrichtung (Universität)“

**Comment by bkerschner** [comment]
Ah cooles Feature! Ich würd aber eher dazuschreiben "Deine Uni oder Studienrichtung fehlt? Gib sie einfach so ein: _Studienrichtung (Universitätsname)_

**Comment by thaider** [comment]
erledigt...
