### ISSUE TITLE
Usability: WYSIWYG-Editor bei Lernunterlage erstellen

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#17]
Wenn ich eine Lernunterlage erstelle und der Wysiwig-Editor geladen ist, ist mir nicht klar wohin ich klicken soll, um mit dem Bearbeiten anzufangen... Kann man einen Cursor irgendwo blinken lassen oder das ganze Usability-technisch so lösen, dass es eindeutig ist? Wenn ich drunter geklickt habe, ist ein blaues Feld mit "+Absatz einfügen" gekommen?!?!?  Das ist sehr verwirrend... Überhaupt finde ich, sollte man das Feld, in dem der Text eingegeben werden kann, klar als Feld kennzeichnen, momentan ist es nur eine weiße Fläche, die sich nicht von der restlichen Seite unterscheidet...

**Comment by bkerschner** [comment]
Über dem Meta-Info-Block ist auch ein blaues Feld, was ist das? Verwirrt etwas... 

Copy und Paste aus MS Word 2010 funktioniert übrigens klaglos, GENIAL, siehe https://test.skriptenforum.net/wiki/Skriptum:Epidemiologie_für_Dummies_(Gerald_Gartlehner)

**Comment by thaider** [comment]
wie wäre es, einen Platzhaltertext zu verwenden (z.B. "Inhalt hier einfügen")? Dann müsste es auch automatisch einen blinkenden Cursor geben...

was meinst du mit dem blauen Feld? den schmalen blauen Streifen direkt über dem Titel? das ist die Fortschrittsanzeige, die sich verändert, wenn der Wert für den Fortschritt angepasst wird...

**Comment by bkerschner** [comment]
das war so ein Feld, das auch erscheint, wenn man den Mauszeiger unter das Metainfo-Feld platzieren bewegt, wo drinsteht "Absatz einfügen". Jetzt seh ich es über dem Metainfo-Feld nicht mehr, hat viell. gesponnen.

Ich finde dieses "Absatz einfügen" - Feld aber sehr verwirrend, ich hab mich jedenfalls nicht getraut drauf zu klicken sondern wollte daneben klicken - was aber nicht geht. Bin dann erst draufgekommen, dass man nur so Text eingeben kann... finde ich sehr unintuitiv, kann man das nicht abschalten?

Die Idee mit dem Platzhaltertext finde ich sehr sehr gut. Ich habs schon woanders erwähnt, würd aber bissl mehr schreiben und auch Überschriften einbinden, zB 

**Erste Überschrift**
Hier kommt dein Text hinein. Bitte gliedere deinen Text mit der Überschriftenfunktion des Editors, damit automatisch ein Inhaltsverzeichnis erstellt werden kann: klicke dazu auf "Standardtext"  und wähle "Überschrift"

**Comment by thaider** [comment]
Template: erledigt (der Text ist in Mediawiki:skrifo-template gespeichert und kann also auch von dir jederzeit angepasst werden)
