### ISSUE TITLE
Fragenausarbeitung erstellen - Wysiwyg-Editor

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#18]
Hmm, ich kann unabsichtlich den Metainfo-Block löschen, kann man das nicht sperren?? Das sollte nicht passieren...

Am besten ist, man kann ihn gar nicht im Editor selbst bearbeiten, und er wird außerhalb vom Editor angezeigt (oder wenn der Editor geladen ist, gar nicht angezeigt)

Es ist auch ein bisschen unklar, wie die Fragenausarbeitung aufgebaut sein soll, bzw wie man den Editor bedienen soll, um einen Text formatiert zu erstellen. Kann man "Absatz" nicht zum Beispiel in "normaler Text" oder "Standardtext" umbenennen?? Sonst glaubt man, man kann da einen Absatz erstellen (was auch immer das heißen soll). Noch besser wäre, wenn auch irgendwo dabeistehen würde, dass das Formatierungsoptionen sind...

Kann man nicht schon ein teilweise befülltes Template laden, wo schon richtig formatiert "1. Hier steht die Prüfungsfrage" und darunter in normaler Textformatierung "Hier steht ein Text, der die Prüfungsfrage ausführlich beantwortet und dann vielleicht darunter dasselbe auch noch für eine zweite Prüfungsfrage.

Solche vorausgefüllten Sachen sollten wir uns auch für neue Skripten überlegen, dann ist gleich klarer, wie es auszusehen hat, und die Skripten werden halbwegs homogen formatiert...

**Comment by thaider** [comment]
Hm, den Metainfo-Block zu sperren (oder zu verstecken), ist leider gar nicht so einfach. Das würde einen ziemlichen Umbau erfordern... wenn das jemandem unabsichtlich passiert, muss die Person ja nicht speichern bzw. hat die Möglichkeit, die Rückgängig-Taste zu benutzen.

„Standardtext“: erledigt

Templates: überhaupt kein Problem - könntest du dir dafür Vorschläge überlegen?

**Comment by bkerschner** [comment]
**Template** siehe hier: https://github.com/thaider/Skrifo/issues/17
dann sollte es auch keine Verwirrung geben. 

**Metainfoblock:** Wir müssen dann nur hoffen, dass die Leute ihn nicht unabsichtlich löschen... Offensichtlich wird der ja nur durch den Code {{Skriptum}} erzeugt - vielleicht wär eine einfachere Möglichkeit, vor dem Speichern zu überprüfen, ob der Code am Anfang noch da ist, und falls nicht, ihn einfach wieder dazuzuschreiben?

**Standardtext:**  irgendwie find ichs noch immer nicht so gut. Wenn ich zB was als Überschrift formatieren will, such ich vergebens danach und komm als DAU wahrscheinlich nicht auf die Idee, auf "Standardtext" zu klicken wenn ich eine Überschriften-Formatierung brauch. Kann man da irgendwie vor das Feld "Textformat:" davorschreiben oder so? Oder wir benennen jede Formatierung in der Art "Textformat: Standard", "Textformat: Überschrift" etc.

Was ist eigentlich der Unterschrift zw. "Überschrift" und "Überschrift 1"?

**Comment by thaider** [comment]
**Metainfo:** ist eher aufwändig, das zu automatisieren - würde ich erst angehen, wenn sich im Betrieb tatsächlich herausstellt, dass da häufig Unfälle passieren...

**Standardtext:** es wird jetzt _Format:_ vor dem ausgewählten Absatzformat angezeigt (nicht aber im Dropdown)

Die Benennung mit "Überschrift" und "Unterüberschrift [1-4]" finde ich auch unglücklich - soll ich es auf "Überschrift [1-5]" ändern?

**Comment by bkerschner** [comment]
sorry für die späte Antwort... es ist ja die Frage, ob wir Überschrift 1 im Text überhaupt verwenden - wenn es dieselbe Überschriften-Kategorie ist, die der Titel des Skriptums hat, sollten wir sie überhaupt nicht für den Text mehr verwenden lassen können, also weglassen. Sonst gerne umbenennen in 1-4 oder 1-5

**Comment by thaider** [comment]
Ich habe die Benennung auf "Überschrift [1-5]" geändert. Mit diesen Formaten werden die HTML-Tags`<h[2-6]>` erzeugt. `<h1>`-Überschriften sind über das Format "Seitentitel" zugänglich (im Dropdown ganz unten). Das könnten wir auch ganz verstecken, da es aber derzeit in einigen Lernunterlagen verwendet wird, könnte das zu Problemen führen...
