### ISSUE TITLE
Neues Skriptum erstellen - vorige Formularzeile ändern

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#19]
Wenn ich ein neues Skriptum erstelle, und irrtümlich bei "Wer leitet bzw. leitete die Lehrveranstaltung?" den Namen der LV eingetragen habe und auf Enter gegangen bin und das dann ändern will, lässt es sich nicht mehr ändern - ich kann den falschen Namen zwar löschen, aber keinen neuen hineinschreiben

**Comment by thaider** [comment]
Hm, bei mir klappt das schon. Was verwendest du denn für eine Browserversion?

**Comment by bkerschner** [comment]
Bei mir wars, als ich schon durch Enter die 2. Formularzeile aufgerufen hab und nachträglich dann noch was in der ersten Zeile ändern wollte. Ich glaub, das war aber ein Usability-Missverständnis meinerseits, weil jetzt gehts, siehe: https://github.com/thaider/Skrifo/issues/23
