### ISSUE TITLE
Usability: Lernunterlage erstellen - Eingabe von neuen Daten in Formular nur mit Enter zu bestätigen

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#23]
Wenn ich den Namen des Lehrveranstaltungsleiters oder den Titel der LV angebe, und die Namen sind noch nicht im System, klappt dennoch die Vorschlags-Box aus, nur dass da nur das drinsteht was ich eingeben will. Eigentlich ist das unnötig und verwirrt, weil ich muss dann den von mir getippten Namen in der Vorschlagsbox extra anklicken, damit er ins Feld übernommen wird. Ich hätte mir erwartet, dass wenn es keine Vorschläge gibt, die ich übernehmen kann (zB schon existierender Eintrag des LV-Leiters) dann sollte auch die Vorschlagsbox verschwinden, und ich sollte den Namen ganz normal in das Feld eingeben können, ohne dass ich Enter klicken muss. Wenn ich nämlich einfach nur schreibe und dann in das Feld neben das getippte klicke, verschwindet das von mir geschriebene wieder...

**Comment by thaider** [comment]
Dieses Verhalten zu ändern ist leider ein wenig komplizierter, weil da das jQuery-Plugin [Select2](http://select2.github.io/examples.html#tags) verwendet wird, dessen aktuellste Version derzeit noch im Beta-Stadium ist. Es ist daher sehr gut möglich, dass etwaige Hacks schon nach dem nächsten Update nicht mehr funktionieren bzw. Nacharbeit erfordern. Gleichzeitig kann es gut sein, dass die AutorInnen das (tatsächlich etwas unintuitive) Verhalten ändern, es gibt immerhin schon ein diesbezügliches [Issue](https://github.com/select2/select2/issues/3808)...

**Comment by thaider** [comment]
vorläufig könnten wir einfach einen Hinweis anbringen („Eingabe mit Enter abschließen“)

**Comment by bkerschner** [comment]
hmm ok, dann sollten wir schaun, ob das vielleicht von vom Select2-Plugin in nächster Zeit behoben wird...
