### ISSUE TITLE
"Teile deine Lernunterlage" und "Jetzt Admin werden" wieder einklappbar machen

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#24]
Ist jetzt nicht hohe Priorität, aber ich würd die beiden Texte wieder einklappbar machen - ausklappen tun sie ja von alleine wenn man auf die Buttons klickt - vielleicht durch einen nochmaligen Klick auf den jeweiligen Button

**Comment by thaider** [comment]
Es gibt ein kleines graues x im rechten oberen Eck des Ausklapptexts - damit kann er wieder eingeklappt werden. Reicht das oder ist das zu wenig offensichtlich?
