### ISSUE TITLE
Lernunterlage lässt sich nicht erstellen

### ISSUE THREAD

**Issue by little-sweety-peanut** [thaider/Skrifo#38]
Egal, welches der drei Icons ich anklicke, es kommt folgende Meldung: Fatal error: Call to a member function exists() on null in /var/www/skrifo/w/extensions/Skrifo/Skrifo.hooks.php on line 82

**Comment by ghost** [comment]
ich kann diesen bug auf windows10/chrome reproduzieren

**Comment by thaider** [comment]
sollte behoben sein...
