### ISSUE TITLE
Lernunterlage suchen und dann Enter bringt verwirrende, generische Ansicht

### ISSUE THREAD

**Issue by ghost** [thaider/Skrifo#40]
wenn ich einen suchbegriff in das kleine suchfenster oben eingebe und dann enter drücke sollte ich direkt zum skript der lernunterlage, zu den prüfungsfragen oder der Fragensammlung kommen?

statt dessen erscheint ein generisches grün schwarzes
"Lernunterlage erstellen/bearbeiten

Welche Lernunterlage möchtest du bearbeiten/erstellen?"

das maaag sinnvoll sein für das erstellen von lernunterlagen, aber für das benutzen der seite als informationssuchender Mensch ist das
- sehr verwirrend
- unpraktisch, umständlich, unelegant
- schlicht nicht beabsichtigt?

Lösungsvorschlag: direkt zu der gesuchten Lernunterlage gelangen nachdem man enter drückt

**Comment by thaider** [comment]
Um den Aspekt der Verwirrung geht's auch in #4, daran arbeiten wir. Die Umständlichkeit werden wir leider nicht ganz weg bekommen, weil die Autovervollständigung im Suchfeld den Titel der Lehrveranstaltung vervollständigt, aber die Benutzerin damit ja noch nicht mitgeteilt hat, an welcher Art von Lernunterlage (Skriptum/Fragenausarbeitung/Prüfungsfragen) sie interessiert ist. Deshalb braucht es den Zwischenschritt, wo angezeigt wird, was es zu einer bestimmten Lehrveranstaltung überhaupt alles gibt. Diese Seite hat aber ganz klar noch Überarbeitungsbedarf. Wenn es konkrete Verbesserungsvorschläge gibt (z.B. für das Wording in der Überschrift), sind wir dafür sehr dankbar!

**Comment by ghost** [comment]
nun, aber wir sind doch in erster Linie ein Wiki, spricht etwas ernsthaft dagegen standardmäßig (zumindest wenn es eines gibt) das Skriptum zur Lehrveranstaltung anzuzeigen?

Das wäre technisch doch sicher umsetzbar, weniger verwirrend und wenig schädlich. Oder sehe ich das falsch?

**Comment by ghost** [comment]
den Text bearbeiten.. "welche Lehrveranstaltung möchtest Du erstellen/bearbeiten?" ist halt der ober-verwirrer wenn man einfach nach einem skriptum sucht und das anschauen möchte.

ist usability mäßig auch einfach nicht akzeptabel, da brauche ich keinen Test für um das rauszufinden. Ist aber wohl technisch kaum änderbar, wenn man nicht ein Duplikat dieser Seite erzeugt, bei dem man dann den Text ändert auf "Welche Lernunterlage möchtest Du zu dem (gefundenen) Thema anschauen". Das würde dann nur angezeigt wenn ein Suchergebnis gezeigt wird.. oder so. Nur mal ein Vorschlag von dem ich nicht weiß ob er umsetzbar ist. Besser fände ich je eh (siehe oberes Kommentar)

**Comment by thaider** [comment]
Nach Rücksprache mit Tim, der das ähnlich sieht wie ihr, habe ich mich von euren Argumenten überzeugen lassen. Falls es zu einer Lehrveranstaltung eine Lernunterlage gibt, wird diese jetzt direkt angezeigt, und zwar folgendermaßen priorisiert: Skriptum vor Fragenausarbeitung vor Prüfungsfragen vor Datei-Lernunterlage.
