### ISSUE TITLE
Nummerierung/Aufzählung Prüfungsfragen

### ISSUE THREAD

**Issue by little-sweety-peanut** [thaider/Skrifo#41]
Aufzählung/Nummerierung der Prüfungsfragen beginnt immer wieder bei 1, wenn man dazwischen unnummerierte Punkte hat.
Unterpunkte wie a) b) o. Ä. wären auch super.

**Comment by thaider** [comment]
Ja, die Lösung, hier Wiki-Markup zu verwenden, ist leider nicht perfekt. Um das Problem zu entschärfen, habe ich die Anleitung etwas ausführlicher gestaltet und an den Rand verschoben. Ist es so besser bzw. hast du noch weitere Vorschläge, wie es klarer formuliert werden kann?

Vielleicht sollte man auch gar nicht auf das Wiki-Markup hinweisen und die Leute die Nummerierung selbst manuell vornehmen lassen. Dann bräuchte es nur den Hinweis, dass für einen Absatz eine Leerzeile eingefügt werden muss.
