### ISSUE TITLE
Überschrift lässt sich nicht ins Feld kopieren

### ISSUE THREAD

**Issue by little-sweety-peanut** [thaider/Skrifo#42]
Wenn man bei einer Ausarbeitung bereits vorher definiert, dass etwas eine Überschrift werden soll bzw. die Vorlage ganz am Anfang befüllt werden soll, kann man in dieses dann grau unterlegte Überschriftenfeld nichts hineinkopieren.

**Comment by thaider** [comment]
Der Fehler scheint aufzutreten, wenn ein Text mit Formatierung (z.B. aus Word oder LibreOffice), die nicht der Zielformatierung entspricht, kopiert wird. Lässt sich nicht ohne weiteres beheben, wir dürfen aber darauf hoffen, dass es in einer zukünftigen Version des VisualEditor ausgebessert wird...
