### ISSUE TITLE
Usability: Möglichkeit für Copy&Paste hervorheben

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#56]
@thaider 

Habe vor kurzem folgende Nachricht auf Facebook bekommen:

_hey, finde die Plattform eine gute Idee ... nur wurde sie in letzter Zeit verschlimmbessert .... wie kann ich eine stinknormale Datei hochladen? ich komme immer nur zu dem fancy Editor, der eben auch schick aussieht, aber ich tu mir das sicher nicht an noch einmal alles zu formatiern_

**Lösungs-Vorschlag:**
1. Copy&Paste-Möglichkeit aus Word erwähnen in Default-Text, der im sonst leeren Visual Editor noch erscheint
2. Evtl eine Mailadresse angeben, an die sich der User wenden kann (zB sowas wie hilfe [ät] skriptenforum.net oder so  
3. eventuell Möglichkeit zum Dateiupload oder Lernunterlage an uns per Mail schicken, die wir dann ins Wikiformat umwandeln, siehe issue #57 (ev. temporärer Service, um mehr Inhalte zu bekommen, ließe sich jederzeit wieder deaktivieren) 

Ich kann einen Vorschlag für einen aktualiesierten Default-Text im Visual Editor machen, wenn wir uns auf eine Möglichkeit geeinigt haben.

**Comment by thaider** [comment]
Kannst du bei dem Autor der Nachricht noch einmal nachfragen, ob er Copy&Paste probiert hat und ob es dabei Schwierigkeiten gegeben hat? Falls ja, welche? Und du kannst ihm ja anbieten, seine Lernunterlage an dich zu schicken, dann kannst du selbst mit einem Real Life-Anwendungsfall testen...

**Comment by bkerschner** [comment]
der User antwortet mir leider nicht... aber bin stark für die Möglichkeit, Unterlagen per Mail zu schicken :) Werd mal den Default-Text ändern
