### ISSUE TITLE
Usability: Möglichkeit zum Datei-Upload / per Email an uns schicken?

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#57]
Manchen Usern fällt es offenbar einfacher, Dateien hochzuladen (siehe issue #56 ).

Ich sehe 2 Möglichkeiten, um diesem Wunsch zu begegnen:
1. Im Default-weise geladenen Text im Visual Editor eine Mailadresse angeben, an die die User wenn sie wollen ihre Unterlagen schicken können
2. Upload-Funktion einrichten für Lernunterlagen in Datei-Form

In beiden Fällen wären die Dateien **nicht öffentlich einsehbar**, sondern wir müssten sie selbst händisch ins Wikiformat umformatieren und dann online stellen. 

**Vorteil:** Wir erleichtern den Leuten den Umgang, die Wikifunktion bliebe dennoch die wesentliche Funktion des Skrifo
**Nachteil:** mehr Arbeit für uns (könnte daher auch nur temporär am Anfang eingesetzt werden), Online-Stellen würde länger dauern für den User

**Comment by thaider** [comment]
Da deutlich weniger aufwendig in der Umsetzung würde ich für den ersten Vorschlag plädieren (Einsenden von Dateien per Mail) – und einfach mal ausprobieren, ob das Angebot in Anspruch genommen wird. Zusätzlich einen klaren Hinweis, dass Copy & Paste normalerweise gut funktionieren sollte.

Bitte mach das am besten einfach selbst, den Defaulttext für neue Skripten/Fragenausarbeitungen kannst du hier ändern: https://www.skriptenforum.net/wiki/MediaWiki:Skrifo-template?action=edit

**Comment by bkerschner** [comment]
done ;-) hab mal upload @ skrifo eingerichtet dafür :) 

Die 2. Variante kömma ja dann ein andermal probieren, oder auch gar nicht, wenn das hier funktioniert, hab jetzt das Label mal auf nice to have gesetzt
