### ISSUE TITLE
Lehrveranstaltungsseite: auf Dateien verweisen

### ISSUE THREAD

**Issue by bkerschner** [thaider/Skrifo#8]
Wenn ich im Suchfeld "Genexpression" eingebe und einen der vorgeschlagenen Suchbegriffe wähle, werde ich zwar zu https://test.skriptenforum.net/wiki/Genexpression_%28Bl%C3%A4si_Udo%29 weitergeleitet, dort sehe ich aber nur "Lernunterlage erstellen / bearbeiten" und nicht das Skriptum... Liegt vielleicht daran, dass es kein Wiki-Skriptum ist...

Wenn ich Biologische Psychologie II suche und wähle, klappts: https://test.skriptenforum.net/wiki/Skriptum:Biologische_Psychologie_II_%28Bauer_Herbert%29 - von dem Skriptum weiß ich, dass es ein Wikiskriptum ist

**Comment by thaider** [comment]
hm, das ist tricky und hat mehrere Aspekte:
- die Autovervollständigung sucht nur nach Seitentiteln, die mit dem Suchbegriff beginnen, findet also bei Eingabe von 'Genexpression' nur die Lehrveranstaltungsseiten wie 'Genexpression (Bläsi Udo)', die wir ja eigentlich so gut wie möglich verstecken wollten, nicht aber 'Prüfungsfragen: Genexpression (Bläsi Udo)'
- auf der Lehrveranstaltungsseite solltest du allerdings erkannt haben, dass es zwar kein Skriptum, aber (wiki-)Prüfungsfragen gibt - dass das deutlicher sichtbar gemacht wird ist Gegenstand von Issue #4 
- in dem Fall gibt es zwar keine Datei-Lernunterlagen, allerdings ist deine Diagnose zutreffend, dass diese über die Lehrveranstaltungsseite nicht zugänglich wären - da ist also jetzt die Frage, wie wir damit umgehen
- aktuell erreicht man Datei-Lernunterlagen entweder über die Suche (z.B. wenn ich nach 'sprachphilosophie' suche werden mir einige Dateien in den Suchergebnissen angezeigt) oder über Verweise in wiki-Lernunterlagen (z.B. hier: https://test.skriptenforum.net/wiki/Pr%C3%BCfungsfragen:Einf%C3%BChrung_in_die_Sprachphilosophie_-_Aspekte_von_Wittgenstein_bis_Brandom_%28Auinger_Thomas%29)

ich würde vorschlagen, die Dateien auch den Lehrveranstaltungsseiten zu verlinken - das wäre dann also wieder eine Gestaltungsaufgabe für Tim ;)

**Comment by bkerschner** [comment]
hmm gute Frage - Datei-Lernunterlagen sind ja eh eine aussterbende Spezies...
